//caminho padrão para imagens
:imagesdir: ../images
:figure-caption: Figura
:doctype: book

//gera apresentacao
//pode se baixar os arquivos e add no diretório
:revealjsdir: https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.8.0

//GERAR ARQUIVOS
//make slides
//make ebook

//Estilo do Sumário
:toc2: 
//após os : insere o texto que deseja ser visível
:toc-title: Sumário
:figure-caption: Figura
//numerar titulos
:numbered:
:source-highlighter: highlightjs
:icons: font
:chapter-label:
:doctype: book
:lang: pt-BR
//3+| mesclar linha tabela

link:https://fagno.github.io/pwebii-spring-ifto/[HOME]

= Programação para Web II
Fagno Alves Fonseca <fagno.fonseca@ifto.edu.br>
Mestre em Modelagem Computacional de Sistemas – UFT.

== Spring Security

Spring Security é uma estrutura de autenticação e controle de acesso poderosa e altamente personalizável. É o padrão de fato para proteger aplicativos baseados em Spring. Se concentra em fornecer autenticação e autorização para aplicativos Java. Como todos os projetos Spring, o verdadeiro poder do Spring Security é encontrado na facilidade com que pode ser estendido para atender aos requisitos personalizados.

Características: 

- Suporte abrangente e extensível para autenticação e autorização;

- Proteção contra ataques como fixação de sessão, clickjacking, falsificação de solicitação entre sites, etc;

- Integração de API de servlet;

- Integração opcional com Spring Web MVC;

- Entre outros.

Para adicionar o Spring Security em nosso projeto web, você deve inserir no `pom.xml` a dependência a seguir:

.pom.xml
[source, xml]
----
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-security</artifactId>
</dependency>    
----

Após adicionar a dependência, sua aplicação já terá o controle de acesso habilitado, com formulário de login padrão. Ao executar o projeto uma senha será disponibilizada no console, utilize `user` como usuário.

== Referências

1. https://spring.io/projects/spring-security

1. https://spring.io/guides/gs/securing-web/